const reporter = require('cucumber-html-reporter');

const options = {
    theme: 'bootstrap',
    jsonDir: 'reports/json', // Path to the JSON reports generated by Cucumber
    output: 'reports/report.html', // Path where the HTML report will be saved
    reportSuiteAsScenarios: true,
    launchReport: true
};

reporter.generate(options);